// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLGH2IuYURtoPRGCpottC3aLn2jTAvWj4',
    appId: '1:797505264176:web:6f9ca3a22cd8797bf4ebf5',
    messagingSenderId: '797505264176',
    projectId: 'zmr-m-6a904',
    authDomain: 'zmr-m-6a904.firebaseapp.com',
    storageBucket: 'zmr-m-6a904.firebasestorage.app',
    measurementId: 'G-ZMLRCYRLP5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhcMNTVKQIG4vtlj7dyEsiLqZtkYeWCVA',
    appId: '1:797505264176:android:eedf200333dcd9fef4ebf5',
    messagingSenderId: '797505264176',
    projectId: 'zmr-m-6a904',
    storageBucket: 'zmr-m-6a904.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBezu7-s9pQhm5UmntRlbzJ-xL2ih8vBWU',
    appId: '1:797505264176:ios:dc1011ac6fc4da55f4ebf5',
    messagingSenderId: '797505264176',
    projectId: 'zmr-m-6a904',
    storageBucket: 'zmr-m-6a904.firebasestorage.app',
    iosBundleId: 'com.example.zmr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBezu7-s9pQhm5UmntRlbzJ-xL2ih8vBWU',
    appId: '1:797505264176:ios:dc1011ac6fc4da55f4ebf5',
    messagingSenderId: '797505264176',
    projectId: 'zmr-m-6a904',
    storageBucket: 'zmr-m-6a904.firebasestorage.app',
    iosBundleId: 'com.example.zmr',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLGH2IuYURtoPRGCpottC3aLn2jTAvWj4',
    appId: '1:797505264176:web:1a784217f3b0d2b2f4ebf5',
    messagingSenderId: '797505264176',
    projectId: 'zmr-m-6a904',
    authDomain: 'zmr-m-6a904.firebaseapp.com',
    storageBucket: 'zmr-m-6a904.firebasestorage.app',
    measurementId: 'G-6MB737QQ6Y',
  );
}
